services:
  odoo:
    build:
      context: .
      dockerfile: 19.0/Dockerfile
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSLMODE=${DB_SSLMODE}
      - ODOO_DB_MAXCONN=${ODOO_DB_MAXCONN:-8}
      - ODOO_WORKERS=${ODOO_WORKERS:-0}

volumes:
  odoo-data:
