#!/bin/bash
set -e

# =============================================================================
# Odoo entrypoint with DO Spaces/S3 and SSL support
# =============================================================================

if [ -v PASSWORD_FILE ]; then
    PASSWORD="$(< $PASSWORD_FILE)"
fi

# Database connection defaults
: ${HOST:=${DB_PORT_5432_TCP_ADDR:='db'}}
: ${PORT:=${DB_PORT:=${DB_PORT_5432_TCP_PORT:=5432}}}
: ${USER:=${DB_ENV_POSTGRES_USER:=${POSTGRES_USER:='odoo'}}}
: ${PASSWORD:=${DB_ENV_POSTGRES_PASSWORD:=${POSTGRES_PASSWORD:='odoo'}}}

# Export PGSSLMODE for libpq (used by psycopg2)
if [ -n "${DB_SSLMODE}" ]; then
    export PGSSLMODE="${DB_SSLMODE}"
fi

# -----------------------------------------------------------------------------
# Generate runtime config addendum for S3/Spaces storage
# -----------------------------------------------------------------------------
RUNTIME_CONF="/tmp/odoo-runtime.conf"
cat > "${RUNTIME_CONF}" <<EOF
; Runtime configuration generated by entrypoint.sh
EOF

# Admin password from environment
if [ -n "${ODOO_ADMIN_PASSWD}" ]; then
    echo "admin_passwd = ${ODOO_ADMIN_PASSWD}" >> "${RUNTIME_CONF}"
fi

# DO Spaces / S3 configuration
if [ -n "${SPACES_BUCKET}" ] && [ -n "${SPACES_ENDPOINT}" ]; then
    cat >> "${RUNTIME_CONF}" <<EOF

; S3/Spaces attachment storage
ir_attachment.location = fs://spaces

[fs_storage]
spaces.protocol = s3
spaces.options = {"endpoint_url": "${SPACES_ENDPOINT}", "key": "${SPACES_ACCESS_KEY}", "secret": "${SPACES_SECRET_KEY}"}
spaces.bucket_name = ${SPACES_BUCKET}
spaces.directory_path = ${SPACES_PREFIX:-odoo}
spaces.optimizes_directory_path = True

[fs_attachment]
fallback_to_db_store = False
autovacuum_gc = True
EOF
fi

# -----------------------------------------------------------------------------
# Build database arguments
# -----------------------------------------------------------------------------
DB_ARGS=()
function check_config() {
    param="$1"
    value="$2"
    if grep -q -E "^\s*\b${param}\b\s*=" "$ODOO_RC" ; then
        value=$(grep -E "^\s*\b${param}\b\s*=" "$ODOO_RC" | cut -d " " -f3 | sed 's/["\n\r]//g')
    fi
    DB_ARGS+=("--${param}")
    DB_ARGS+=("${value}")
}
check_config "db_host" "$HOST"
check_config "db_port" "$PORT"
check_config "db_user" "$USER"
check_config "db_password" "$PASSWORD"

# Add SSL mode if specified
if [ -n "${DB_SSLMODE}" ]; then
    DB_ARGS+=("--db_sslmode")
    DB_ARGS+=("${DB_SSLMODE}")
fi

# Include runtime config
EXTRA_ARGS=()
if [ -s "${RUNTIME_CONF}" ]; then
    EXTRA_ARGS+=("--config=${RUNTIME_CONF}")
fi

case "$1" in
    -- | odoo)
        shift
        if [[ "$1" == "scaffold" ]] ; then
            exec odoo "$@"
        else
            wait-for-psql.py ${DB_ARGS[@]} --timeout=30
            exec odoo "$@" "${DB_ARGS[@]}" "${EXTRA_ARGS[@]}"
        fi
        ;;
    -*)
        wait-for-psql.py ${DB_ARGS[@]} --timeout=30
        exec odoo "$@" "${DB_ARGS[@]}" "${EXTRA_ARGS[@]}"
        ;;
    *)
        exec "$@"
esac

exit 1
